# See https://github.com/DavidAnson/markdownlint-cli2
config:
  # Disable all rules by default.
  default: false

globs:
  - '**/*.md'

ignores:
  - 'node_modules/**'
  - '**/node_modules/**'
  - 'test/**/*.md'

fix: true
noProgress: true
